### ISSUE TITLE
With recent update, it appears we're restricted to only one floating player

### ISSUE THREAD

**Issue by prech** [gabrielbarros/floating-player#1]
Previously, we had the ability to access multiple floating windows. Essentially, with every open tab, I could run the extension and a new floating player opens. Now, when I run/select the extension with an open tab, the existing floating player window is replaced by the new tab's contents. 

Would really appreciate correcting this so we're allowed multiple floating players.

Thank you!

Extension version: 2.0.15
Chrome Version 60.0.3112.90
Latest as of Aug 9, 2017

PS -- Hope you don't mind, also shared this issue at the [Chrome Extension page](https://chrome.google.com/webstore/detail/floating-player-youtube-t/ekajjllcmeckibblgckgoceinmmgnfop/support?hl=en).

**Comment by gabrielbarros** [comment]
Hey!

Go to chrome-extension://lcdfgfcmhlhlpcbikdeaholjgknefjgg/options.html

Just uncheck the option "Keep current popup instead of opening a new one"

Have a nice day!

**Comment by prech** [comment]
Thanks much, good sir. Works beautifully now

I had no idea the options menu existed, much less the "Keep current popup..." feature was available. Was this a new implementation in version 2.0.15, such that tabs defaulted to separate popups previously?

**Comment by gabrielbarros** [comment]
Actually this was implemented in version 1.9.5 on June 28th. I don't know why it took so long for you to receive the update.
