### ISSUE TITLE
[suggestion] Middle click event

### ISSUE THREAD

**Issue by SunStroke74** [gabrielbarros/floating-player#10]
Is it possible to open player window by mouse middle click in addition of context menu?
Or maybe Ctrl+Middle Click to not interfere with standard browser action...

**Comment by gabrielbarros** [comment]
No. Some script would have to be injected into every page in order to work, which is not secure.

The best you can do is go to chrome://extensions, at the bottom of the page look for "keyboard shortcuts", then associate a shortcut to this extension, like Alt+Q.
