### ISSUE TITLE
Feature Request: Add Setting to Show Horizontal and Vertical Scrolling 

### ISSUE THREAD

**Issue by magi44ken** [gabrielbarros/floating-player#11]
Hi,

Can you an a setting where the user can enable or disable horizontal and vertical scrolling so that you can reposition so fit the size of the video for those that don't properly resize the video within the popup window?

Also add this to the context menu so one can easily disable and enable in the player's window without going to the setting. Example: Once you reposition the video to fit the window size, you want to disable scrolling using context menu.

Another solution is to enable the user to drag the content to reposition the video to fit the window size.

Thanks.

**Comment by gabrielbarros** [comment]
No. Changing the content of web pages is beyond the scope of this extension.

Note that when the page cannot be embedded, the URL receives a "?floating_player=1" at the end, and thereby you can use the Tampermonkey extension to modify the page based on the URL using javascript or css.

If you need help with any particular website, just tell me so I can try to help you, okay?
