### ISSUE TITLE
Youtube doesn't respect the playback speed setting anymore

### ISSUE THREAD

**Issue by StormtrooprDave** [gabrielbarros/floating-player#12]
I haven't used this long but am using the player extension with the Chrome OS add on to stay on top.  It used to work perfectly and obey the playback speed setting but has stopped in the last few days and defaults to 1x every time.  Has something changed?

**Comment by gabrielbarros** [comment]
Actually the add-on never supported the YouTube API, therefore never supported the playback speed setting. You can only set it manually, like this:

![img](https://user-images.githubusercontent.com/3298817/38450532-c4318a98-39f5-11e8-870d-287087939acb.png)

**Comment by StormtrooprDave** [comment]
But why is it in the extension options?

**Comment by gabrielbarros** [comment]
That option only works for the extension, but it doesn't work for the add-on for now. Then you can use such feature on windows and linux only.

**Comment by StormtrooprDave** [comment]
Ah right, it must have followed the speed setting at first but then I
needed the add on as well to stay on top in Chrome OS. I understand now.
Thanks for your work anyway.
