### ISSUE TITLE
ALWAYS ON TOP TUTORIAL

### ISSUE THREAD

**Issue by gabrielbarros** [gabrielbarros/floating-player#14]
# ALWAYS ON TOP TUTORIAL

The "always on top" function is not available for extensions, only for packaged apps, which have been [deprecated by Google](https://gist.github.com/gabrielbarros/4bea0cfc622e1b090874df4a55b0c09f) and cannot be uploaded and are not listed on Chrome Webstore anymore.

If you want that function to be available for extensions, please login to your Google account and star this issue (but please don't post comments such as "like" or "+1"):
https://bugs.chromium.org/p/chromium/issues/detail?id=822425

For now, we have two options: either install a 3rd-party software or install manually our packaged app.

## 3rd-party software

1. If you are using Windows, install one of these to enable "always on top":
    - [Deskpins](https://bitbucket.org/efotinis/deskpins/downloads/DeskPins-1.32-setup.exe)
    - [4t Tray Minimizer Free](http://www.4t-niagara.com/tray.html)
    - [AutoHotkey](https://autohotkey.com/)
    - [TurboTop](https://www.savardsoftware.com/turbotop/)

2. If you are using Linux, just right click the title of the popup and then click "Always on top"

3. If you are using macOS, install [Helium](https://itunes.apple.com/app/helium/id1054607607) or [HeliumLift](https://itunes.apple.com/app/heliumlift/id1018899653), then go to the options page and check the option "Open video with Helium on macOS" and select "Helium" or "HeliumLift", as appropriate.

4. If you are using ChromeOS, install our [add-on for ChromeOS](https://chrome.google.com/webstore/detail/neefhpglbgbkmlkgdgkfoofkcpbodbfb), then go to the options page and check the option "Open popup using addon on Chrome OS"

## Packaged app

As I said earlier, you can also install manually our app if you don't want or are unable to install a 3rd-party app. But keep in mind that eventually it will stop working as soon as Google removes support for Chrome apps on Windows, macOS and Linux.

-  Download https://github.com/gabrielbarros/floating-player-app/archive/master.zip
-  Unzip it
-  Move the folder `floating-player-app-master` to somewhere safe (Documents, Desktop, etc)
-  Open Google Chrome
-  Go to `chrome://extensions/`
-  Check "Developer mode"
-  Click the button "Load unpacked extension"
-  Select the folder `...\floating-player-app-master\src` (<-- SRC FOLDER!)
-  Go to the options page: `chrome-extension://ekajjllcmeckibblgckgoceinmmgnfop/options.html`
-  Press F9
-  Click "Allow" and test it on YouTube
-  If you want to disable it, press F9 again on the options page

### Advice

If you are using Windows, I really recommend that you use Deskpins. It's a must-have app that enables a function that's not available for Windows natively. Very easy to use, only 105 kB and it's open source (https://bitbucket.org/efotinis/deskpins)!

DeskPins stays in your system tray. Click the icon and your cursor will turn into a pin and then click the popup so that it keeps pinned to the top of your screen.

**Comment by asfo** [comment]
I use this extension also, which doesn't require any "extra apps" or "do this, do that", I think you could try to check how it do it and copy it to this extension which I think it was almost what I was looking because I can open Twitch, and other videos (not only YouTube) in a small screen :)

https://chrome.google.com/webstore/detail/floating-for-youtube/jjphmlaoffndcnecccgemfdaaoighkel?hl=es-419

**Comment by gabrielbarros** [comment]
hi, @asfo. The other extension "Floating for YouTube" requires a packaged app. That's why it can make the popup on top out of the box. As I said, packaged apps are deprecated and cannot be uploaded anymore.
