### ISSUE TITLE
Large more videos popup is annoying

### ISSUE THREAD

**Issue by austin6598** [gabrielbarros/floating-player#18]
Please disable the class ytp-pause-overlay so that the More Videos overlay doesn't show or at least have an option for this.

**Comment by gabrielbarros** [comment]
Hi, @austin6598 

Do you mean the related videos? You can disable them. Just go to the options page and uncheck the option "Show related videos".

chrome-extension://ekajjllcmeckibblgckgoceinmmgnfop/options.html

Have a nice day!
