### ISSUE TITLE
A choice of monitor

### ISSUE THREAD

**Issue by alyldas** [gabrielbarros/floating-player#19]
Please add the possibility to choose the monitor on which the player will be opened.

**Comment by gabrielbarros** [comment]
That's not possible.

But there's a trick. For example, let's say the resolution of your first monitor is 1366x768 and your second monitor is 1920x1080.

If you want the popup to stay on the top right or bottom right corner of your second monitor, go to the options page and set horizontal margin to -1920 (negative sign!)

But if you want the popup to stay on the top left or bottom left corner, set horizontal margin to 1366.

**Comment by alyldas** [comment]
Thank you!
