### ISSUE TITLE
Add a "preferred mode" option to settings.

### ISSUE THREAD

**Issue by GinSakata** [gabrielbarros/floating-player#2]
When playing a playlist if one video fails to play in embedded mode, the extension will load that and every next video in Youtube TV or Youtube website.

It would be nice to be able to select a preferred mode that the extension will try to force in every video of a playlist.

**Comment by gabrielbarros** [comment]
Once you're on YouTube TV, there's no going back. If you don't like YouTube TV, you can uncheck the option "Play video on YouTube TV if it cannot be embedded". Then when you're playing a playlist and one video fails, you can just skip it.
