### ISSUE TITLE
Missing scrollbars on Firefox for non supported websites

### ISSUE THREAD

**Issue by pemartins1** [gabrielbarros/floating-player#20]
At least in Ubuntu, the Firefox version is missing scrollbars for non supported websites. In example, if you go to a random website like https://alphabetizer.org/, in Chrome you have a normal window with scrollbars as expected which you can use to move around inside the window:

![chrome](https://user-images.githubusercontent.com/23001662/40874552-c3253ba0-6668-11e8-98ac-e5bd8ac99c0d.png)

On the other hand in Firefox the scrolbars do not show, leaving the user stuck without any chance of moving around and not even the cursor keys work:

![firefox](https://user-images.githubusercontent.com/23001662/40874611-29834806-6669-11e8-9aa2-6e032546016f.png)

pt
Resumo em português, estão a faltar as barras de deslocação no Firefox em sites sem players ou sem players suportados na extensão, ficamos agarrados à parte superior do ecrã e dali não dá para sair.

Parabéns pela excelente extensão que é super útil!
Abraço

**Comment by gabrielbarros** [comment]
Hi, @pemartins1. You're right. It seems that there's a bug in Firefox. :cry:

I'll report it to Bugzilla as soon as possible.

**Comment by gabrielbarros** [comment]
It seems it was fixed:

![imgg](https://user-images.githubusercontent.com/3298817/44753963-4f112300-aaf6-11e8-8557-1a5b18b5f781.png)
