### ISSUE TITLE
Logo Design Contribution Offer

### ISSUE THREAD

**Issue by ihtiht** [gabrielbarros/floating-player#21]
Hi, 

I am a graphic designer. I contribute to open source projects by making designs. At the same time I am creating a portfolio. You can look at my previous studies from my profile. If you want, I can design a logo for Floating Player.

**Comment by gabrielbarros** [comment]
Hi @ihtiht

**Comment by gabrielbarros** [comment]
Hi @ihtiht 

I really thank you but I want to keep the current logo, which is fairly simple.
