### ISSUE TITLE
Doesn't work for a local stream from url only

### ISSUE THREAD

**Issue by ks2018ks** [gabrielbarros/floating-player#22]
Hi - tried opening this stream in my chrome:
http://192.168.1.25/live/0/mjpeg.jpg (this normally shows the stream from an IP camera)
Clicked the Floating Player icon 
Nothing happened.

**Comment by gabrielbarros** [comment]
Hi, @ks2018ks 

Here it's working from localhost:

![img](https://user-images.githubusercontent.com/3298817/43522713-90e93998-9570-11e8-8cdd-35588cffdc00.png)
-----

Go to `chrome://extensions/?id=ekajjllcmeckibblgckgoceinmmgnfop`, click "background.html" and click "Console" tab. Then open your stream link and click the floating player icon. See if some error appears on the console.
