### ISSUE TITLE
douyu.com & panda.tv not working please update for it ! thank you

### ISSUE THREAD

**Issue by ichankhi** [gabrielbarros/floating-player#24]
douyu.com & panda.tv not working 
please update for it ! thank you
![untitled](https://user-images.githubusercontent.com/17388783/44599080-56d37d80-a7ff-11e8-8cd3-ecb3b216a50e.png)

**Comment by gabrielbarros** [comment]
Most websites will be supported as of Chrome 69. Just wait until september 4th and do the following:

- Update your browser. Go to chrome://settings/help and wait for the update. Maybe you'll have to wait a few more days to get Chrome 69. Be patient.

- Update your extensions. Go to chrome://extensions, check "Developer mode" and click the button "Update".

- Go to chrome://flags/#enable-picture-in-picture and select "Enabled".

- Go to chrome://flags/#enable-surfaces-for-videos and select "Enabled".

- Restart your browser.

**Comment by gabrielbarros** [comment]
Flags:

![flags](https://user-images.githubusercontent.com/3298817/44666769-7f21ce80-a9ef-11e8-96a5-467a9d930162.png)


----

Chrome 69 required:

![chrome-69](https://user-images.githubusercontent.com/3298817/44666780-83e68280-a9ef-11e8-84f6-4a14f2c94502.png)


---
douyu.com with native picture-in-picture:

![site](https://user-images.githubusercontent.com/3298817/44666787-8812a000-a9ef-11e8-87b1-b041c4b346bc.png)
