### ISSUE TITLE
I'd like to (try to) extend this beyond YouTube, Twitch and others

### ISSUE THREAD

**Issue by conjenks** [gabrielbarros/floating-player#26]
Hi Gabriel. I've been absolutely loving this. Keeping a Twitch stream in the corner while doing homework is so great. Above anything: thank you.

However, it doesn't work quite the same for Hulu; the initial display doesn't include the entire picture and needs to be rescaled/enlarged to show the whole frame. I'd like to change that because I love Hulu shows like "It's Always Sunny in Philadelphia" etc. 

If possible, could you give me a quick overview of how it all works? (I know how to code, just a simple architecture explanation would be nice) And where to start when trying to add built-in functionality for other streaming services? Any insight would be appreciated, but if it's not worth your time I understand. Again, thank you for this.

**Comment by gabrielbarros** [comment]
> Above anything: thank you.

Cool. You're welcome.

> However, it doesn't work quite the same for Hulu

Do you have a screenshot? I tried to sign up for Hulu, but it's not available in my country and VPNs/proxies are also blocked.

> If possible, could you give me a quick overview of how it all works?

Are you using Chrome 70 with the native player? If so, it's just:

    document.getElementsByTagName('video')[0].requestPictureInPicture(); // and forget everything else...

> [...] add built-in functionality for other streaming services

We have no control over the native player. We can't change width, height, position, video quality, controls, etc. But if you're talking about the popup player, then I can explain it better.
