### ISSUE TITLE
Unable to change size of video

### ISSUE THREAD

**Issue by izaakio** [gabrielbarros/floating-player#27]
Hi Gabriel,

I love floating player, ive been using it for a little over a month and it's incredibly useful. Thank you for providing this!

I cannot seem to change the size of the video, as in, no matter what I set the size to in settings, it's always the same, about 250x150 pixels and it's not large enough for me. I'm not sure what I need to do!

I'm using chrome on windows 10 with an nvidia gtx1050, hdmi output.

**Comment by gabrielbarros** [comment]
Hi @izaakio 

Resize a window by dragging the edges or corner of the window, like this:

![ezgif-1-0f1b8911a22d](https://user-images.githubusercontent.com/3298817/47868568-42a19300-dde3-11e8-9fa8-af78b8cc2b0a.gif)

At the moment we cannot set the width or height for native picture in picture.

Go to the options page and uncheck "Use native Picture in Picture" to show the browser popup which supports width, height and position. In this case you'll need to install Deskpins to keep the popup always on top.

**Comment by izaakio** [comment]
Thank you so much Gabriel!

**Comment by gabrielbarros** [comment]
You're welcome. Have a nice day!
