### ISSUE TITLE
[suggestion] Always on Top option?

### ISSUE THREAD

**Issue by NNickey** [gabrielbarros/floating-player#3]
Finally, an extention that actually has correct permissions, and has an amazing intergration to how it opens youtube, using timeframes and pausing!

However, I thought the popup would 'stay on top' till i clicked back on chrome, and my hopes were let down after I tried looking for 'AOT/Always on Top' in the settings..

Is it possible that you'll add this feature?

**Comment by gabrielbarros** [comment]
Unfortunately that's not possible out of the box.

If you're using Windows, you can install [Deskpins](https://bitbucket.org/efotinis/deskpins/downloads/DeskPins-1.32-setup.exe) to keep the popup always on top, according to the instructions given.

------------------

But there is a workaround. Follow the instructions below step-to-step carefully:

- Download https://github.com/gabrielbarros/floating-player-app/archive/master.zip

- Unzip it

- Move the folder "floating-player-app-master" to somewhere safe (Documents, Desktop, etc)

- Open Google Chrome

- Go to chrome://extensions/

- Check "Developer mode"

- Click the button "Load unpacked extension"

- Select the folder ...\floating-player-app-master\src (<--- SRC FOLDER!)

- Copy its id (32 letters), below Details / Launch / Reload (Ctrl+R)

- Go to chrome-extension://ekajjllcmeckibblgckgoceinmmgnfop/options.html

- Press F12

- Click Console tab

- Type (replace XXXXXXX with the id you copied):

```
localStorage.appid = 'XXXXXXX';
document.querySelectorAll('.only-chrome-os').forEach(function(e) { e.style.display = 'block' });
```

- Press F12 to close devtools

- Check the option "Open popup using addon on Chrome OS"

- (optional) Check the option "Remove borders and title bar[...]"
