### ISSUE TITLE
Chrome freezing with floating players running? v2.0.28

### ISSUE THREAD

**Issue by prech** [gabrielbarros/floating-player#4]
Thanks for the great work, I use Floating Player almost everyday!

Unfortunately, I've noticed some strange behavior. Would it be possible to investigate if Floating Player is conflicting with the newer Chrome versions? Ever since Chrome updated a few weeks ago to version 62 (I'm now using v62.0.3202), I've noticed consistent freezing of Chrome with Floating Player running.

I've tried using Chrome 63 (Beta) and 64 (Dev v64.0.3269.3) and the same freezing appears to be happening. I've disabled all extensions to eliminate the culprit, with only Floating Player enabled. 

Basically, with Floating Player running, if a Chrome alert message pops up (like to request permission to use my location, to offer to save a password/form fill, or to edit a bookmark), Chrome freezes completely. Floating Player operates without issue until the Chrome alert box pops up. Then everything is frozen and I cannot click on any tabs, or even the upper corner "X" to close the Chrome window.

Please see a screenshot below (or at [https://i.imgur.com/Cgkocbq.jpg](https://i.imgur.com/Cgkocbq.jpg))
![image](https://user-images.githubusercontent.com/8314103/33047651-b485e1bc-ce0b-11e7-8863-3160b5a335cb.png)
Here, I have a new Chrome Dev window with no installed extensions except Floating Player (with DeskPins). I randomly created a bookmark and right clicked on the bookmark to edit it. As soon as the Chrome pop-up "Edit bookmark" box appears, Chrome is completely frozen and I have to force close it in Task Manager.

I'm using Windows 10, Floating Player v2.0.28

Any suggestions/ideas appreciated. Thanks!

**Comment by gabrielbarros** [comment]
Thanks for letting me know, @prech 

Well, I've tested it with Windows 7 and it's working fine. I can't test it with Windows 10 right now but I'll do it in a few days.

For now you can try the following alternatives:

1. [Download 4t Tray Minimizer Free](http://www.4t-niagara.com/tray.html). After installing it, right click the popup title then click "Stay on top", like this:
![fkz2trx](https://user-images.githubusercontent.com/3298817/33050154-8b236936-ce4a-11e7-9f01-80d0fc7677cd.png)

I think it's a good idea to disable the "additional titlebar buttons":

![2017-11-20 23_34_08-4t tray minimizer options](https://user-images.githubusercontent.com/3298817/33050358-a895f5e6-ce4b-11e7-95ad-4a0fb9c004a8.png)

---------

2. Use the Floating Player add-on, [following these instructions carefully](https://github.com/gabrielbarros/floating-player/issues/3#issuecomment-340237956).

---------
Let me know if one of these alternatives worked for you. Have a nice day!

**Comment by prech** [comment]
Thanks @gabrielbarros, really appreciate the suggestions and prompt response.

I tried out both alternatives. Interestingly, 4t Tray Minimizer is working well, and when using it, instead of DeskPins, I've encountered no freezing and Floating Player has worked well after at least 5 attempts with a Chrome alert pop-up :)

When I tried DeskPins again, unfortunately, sure enough, Chrome froze immediately when I pinned a Floating Player on top with the Chrome alert pop-up -- this seems to suggest it's the combination of DeskPins-Floating Player that's responsible. I also used DeskPins to pin some other items like an image editor and text editor, and those didn't lock up Chrome, so it seems it's interacting in some fashion with Floating Player.

Thanks also for the Addon for Floating Player alternative. I did give that a try, and enabled the "Open popup using addon on Chrome OS" option, but unfortunately, Floating Player stopped loading altogether after enabling the Addon. I had to go back to the Floating Player options menu and disable the "Open popup..." parameter to get Floating Player to load, at all. Every time I clicked on the Floating Player icon in the Chrome menu, nothing would happen -- no pop up video window. So unfortunately, I wasn't able try out the pinning/stay on top feature as there was no player window to attempt it on.

For reference, I'm using Windows 10 Pro, 64-bit, version 1709.

Thanks

**Comment by gabrielbarros** [comment]
You said Floating Player stopped loading after enabling the Addon? Probably you copied the wrong ID!

Check this out:

![1x](https://user-images.githubusercontent.com/3298817/33056284-eaffa5b0-ce6b-11e7-8e99-d8aaf3d78325.png)
-----
![2](https://user-images.githubusercontent.com/3298817/33055975-fa0f5502-ce69-11e7-96bc-90cef9311264.png)
------
![3](https://user-images.githubusercontent.com/3298817/33055978-fdf3f236-ce69-11e7-8c1d-06c972720844.png)
--------
![4](https://user-images.githubusercontent.com/3298817/33055983-01efa722-ce6a-11e7-8849-b4237829fae0.png)
--------
![5](https://user-images.githubusercontent.com/3298817/33056108-c3f9a87c-ce6a-11e7-9f8d-a4bf039a75ee.png)

**Comment by prech** [comment]
Thanks, Gabriel -- I was indeed using the Floating Player extension ID for the Javascript. Using the Addon for FP ID worked to re-enable FP for my videos, but unfortunately, the "Open popup using addon on Chrome OS" option didn't force the player window to stay on top. Any clicks or open applications would appear over the Floating Player.

I've still been having success with 4t Tray Minimizer. No crashes yet after several attempts, and it seems more reliable than DeskPins, which exited by itself every day or two for me.

**Comment by gabrielbarros** [comment]
The popup must stay above the taskbar, so you have to increase the vertical margin to 40 or 50. Give it a try!

**Comment by prech** [comment]
Thanks, Gabriel. I had set the vertical margin to 40, then tried 50 and 60, but the same. Any other application or window still seems to take priority

**Comment by gabrielbarros** [comment]
Okay. Well at least 4t Tray Minimizer worked well for you 😊

**Comment by prech** [comment]
Thanks for all the troubleshooting tips, Gabriel. 

May I ask if you or others have reproduced the Chrome freezing issue with Floating Player and DeskPins?

**Comment by gabrielbarros** [comment]
I just tested Floating Player on Windows 10 and it's working fine. No freezing.

Tested with Windows 10 Version 1703 Build 15063.726 on Chrome 62.0.3202.94 64-bit
