### ISSUE TITLE
Youtube Watch Later Playlist only opens first video

### ISSUE THREAD

**Issue by brunomptorres** [gabrielbarros/floating-player#5]
When loading the "Watch Later" Youtube playlist, instead of opening a playlist only the first video of said playlist is opened.

**Comment by gabrielbarros** [comment]
Hi, @brunomptorres 

The Watch Later playlist cannot be embedded.

But you can create a public playlist and move all your videos from Watch Later playlist to it, like this:

![1](https://user-images.githubusercontent.com/3298817/34012331-7e6c6dba-e0fa-11e7-922d-ac1f4cd71c17.png)

![2](https://user-images.githubusercontent.com/3298817/34012336-83149522-e0fa-11e7-8a1b-fa3fb2797390.png)
