### ISSUE TITLE
Remove the window frame

### ISSUE THREAD

**Issue by Zingam** [gabrielbarros/floating-player#6]
Can the window frame be removed? And also drag around the window when click and hold on the window?

**Comment by gabrielbarros** [comment]
Unfortunately that's not possible out of the box.

------------------

But there is a workaround. Follow the instructions below step-to-step carefully:

- Download https://github.com/gabrielbarros/floating-player-app/archive/master.zip

- Unzip it

- Move the folder "floating-player-app-master" to somewhere safe (Documents, Desktop, etc)

- Open Google Chrome

- Go to chrome://extensions/

- Check "Developer mode"

- Click the button "Load unpacked extension"

- Select the folder ...\floating-player-app-master\src (<--- SRC FOLDER!)

- Copy its id (32 letters), below Details / Launch / Reload (Ctrl+R)

![1](https://user-images.githubusercontent.com/3298817/34390474-1ac4fef8-eb27-11e7-8a61-162cc8e9bb0a.png)

- Go to chrome-extension://ekajjllcmeckibblgckgoceinmmgnfop/options.html

- Press F12

- Click Console tab

- Type (replace XXXXXXX with the id you copied):

```
localStorage.appid = 'XXXXXXX';
document.querySelectorAll('.only-chrome-os').forEach(function(e) { e.style.display = 'block' });
```

![2](https://user-images.githubusercontent.com/3298817/34390499-41393ac2-eb27-11e7-9bd6-a59e0dcd8e65.png)

- Press F12 to close devtools

- Check the option "Open popup using addon on Chrome OS"

- Check the option "Remove borders and title bar[...]"

- Increase the vertical margin if needed

![3](https://user-images.githubusercontent.com/3298817/34390509-58ade4fa-eb27-11e7-8cd7-555b27687626.png)

------------------------------

Result:

![4](https://user-images.githubusercontent.com/3298817/34390522-695d0ef2-eb27-11e7-904f-59fbb8790169.png)

*Note that you cannot drag the window*

**Comment by Zingam** [comment]
Thank you very much for the detailed explanation. Are you planning to add these enhancements incl. dragging out of the box?

**Comment by gabrielbarros** [comment]
You're welcome.

Unfortunately Google will remove all apps from Chrome Web Store in mid-2018, therefore the addon for Floating Player will stop working as well.

But Chrome extensions - like Floating Player - will continue working normally.

For now using only the extensions API it's impossible to create a borderless popup or keep a popup always on top without 3rd party applications.
