### ISSUE TITLE
Up Next Videos

### ISSUE THREAD

**Issue by cabaalexander** [gabrielbarros/floating-player#8]
Is it possible to continue with the next up video after the current video/playlist finishes? 🤔

**Comment by gabrielbarros** [comment]
Hi @cabaalexander 
Isn't this the current behavior? When a video ends, the next video in the playlist starts.
If you want the playlist to restart, just check the option "Loop YouTube videos and playlists" at chrome-extension://ekajjllcmeckibblgckgoceinmmgnfop/options.html

**Comment by cabaalexander** [comment]
Yes yes, I haven't opened a playlist yet. But I tried the `loop` option with a single video.

Using the `loop` option on a single video is ok when you found a really good song that you want to burn until you hate it. XD

But what I mean is to continue play the `recommended videos` which is really nice to descover new related or the new videos of your subscriptions. Dunno, it depends of the youtube API. 🤔 

Example:

![image](https://user-images.githubusercontent.com/12496574/35985657-83f06030-0ccd-11e8-8aa1-8a9b8b6c8fad.png)

**Comment by gabrielbarros** [comment]
Ooh I see, the recommended videos. Unfortunately it's not possible as far as I know.

The best thing you can do is check the option "Show related videos". When a video ends, you'll see a list with related videos, then you can right click them and "Open link in popup", like this:

![img](https://user-images.githubusercontent.com/3298817/35994492-bd8d16e2-0cf7-11e8-922a-266ab77c8204.png)

You can also turn a search into a playlist instantly. Just go to YouTube, search for anything, and then click the Floating Player icon in the upper-right corner of the screen. Too bad it only supports 20 videos at most.

Test with this link: https://www.youtube.com/results?search_query=install+ubuntu

**Comment by cabaalexander** [comment]
Ow man! That does the work :DDD

The only thing is that you need to do it manually but I buy it! XD

💯
