### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by brogan89** [gabrielbarros/floating-player#9]
Hey loving the extension on Firefox
Is it possible to make the window always stay on top of the desktop? Or an option or something.

Thanks

**Comment by gabrielbarros** [comment]
Hey @brogan89 

Unfortunately there's no way out-of-the-box.

Using Windows? Try [Deskpins](https://bitbucket.org/efotinis/deskpins/downloads/DeskPins-1.32-setup.exe).

**Comment by brogan89** [comment]
Great that worked perfectly. Thank you!
